### ISSUE TITLE
Airpair website down

### ISSUE THREAD

**Issue by onomated** [fervisa/accounts-react-rails#4]
@fervisa Don't know if you're aware of it, but airplay.com is down.  Don't think you would want to lose that SEO standing as the top link in [react for rails developers google search](https://www.google.com/?q=react%20for%20rails%20developers).

Thanks for a great tutorial btw!

**Comment by fervisa** [comment]
Thanks for the heads-up @onomated I think the issue fixed itself 😛 . BTW, glad you enjoyed the post.
